name: online_coaching
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2
  flutter_rating_bar: ^4.0.1

  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.2
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  cloud_firestore: ^4.4.4
  video_player:
  firebase_database: ^10.0.15
  flutter_gif: ^0.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/gifs/leg/
    - assets/gifs/chest/
    - assets/gifs/cardio/
    - assets/gifs/arm/
    - assets/gifs/back/
    - assets/gifs/shoulder/